name: Test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      test_string:
        description: 'test input string'
        required: false
        type: string
        default: 'https://api.github.com/repos/ZZZ/000/releases/310115652'
  
jobs:
  t_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'zacharee/RootActivityLauncher'
          ref: 'master'
          fetch-depth: 0
      - run: |
          ls
          pwd
          git checkout e3d441b10c9ad34805878c6b3e0e93c9a2ee539a
          git status
          
      - run: |
          echo a-"${{ github.event.inputs.test_string }}"
      - run: |
          r=$(echo ${{ github.event.inputs.test_string }} | grep -iPo 'https?://.+?/repos?/\K.+?/[^\/]+' || true)
          echo "TEST_ENV=$r" >> $GITHUB_ENV
          echo $r
      - name: ${{ env.TEST_ENV }}
        run: echo $TEST_ENV
      - run: mkdir dl
      - run: |
          # set -x
          pwd
          cd dl
          pwd
          # cd -
          # pwd
      - run: |
          pwd
          cd dl
          pwd
