name: Test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      test_string:
        description: 'test input string'
        required: false
        type: string
  
jobs:
  t_1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          r=$(echo ${{ github.event.inputs.test_string }} | grep -iPo 'https?://.+?/repos?/\K.+?/[^\/]+' || true)
          echo $r
      - run: mkdir dl
      - run: |
          set -x
          cd dl
          pwd
          # cd -
          # pwd
      - run: |
          pwd
          cd dl
